version: "3.3"

services:
  app:
    image: ctrillo/uwsgi-nginx-flask:latest
    build: 
      context: .
    environment:
      - PYTHONUNBUFFERED
      - FLASK_DEBUG
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    volumes:
      - .:/app
    ports:
      - 80:5000
  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create-table.sql

  client:
    image: jfahrer/checker-u-dev-a3:latest
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=demo
      - POSTGRES_HOST=pg
