version: "3.3"

services:
  pg:
    image: postgres:9.6.6-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapp:
    image: jfahrer/demo_web_app:wait_for_pg
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    ports:
      - 9292:9292
    depends_on:
      - pg

volumes:
  pgdata:
